services:
  postgres:
    image: postgres:17
    container_name: yacos-postgres
    environment:
      POSTGRES_DB: yacos
      POSTGRES_USER: yacos
      POSTGRES_PASSWORD: yacos
    ports:
      - "3333:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: